steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "apps/api/Dockerfile",
        "-t",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/ocr-platform/credential-lens-api:$BUILD_ID",
        "."
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/ocr-platform/credential-lens-api:$BUILD_ID"
      ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "credential-lens-api",
        "--image",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/ocr-platform/credential-lens-api:$BUILD_ID",
        "--region",
        "asia-south1"
      ]
images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/ocr-platform/credential-lens-api:$BUILD_ID
